const iconeJavascript = 'https://upload.vectorlogo.zone/logos/javascript/images/239ec8a4-163e-4792-83b6-3f6d96911757.svg';
const iconeHTML = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg';
const iconeCSS = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg';
const iconeTailwind = 'https://user-images.githubusercontent.com/106452876/222272710-d163957e-5ec1-4d91-b0b0-501287eb56a4.svg';
const iconeBootstrap = 'https://upload.vectorlogo.zone/logos/getbootstrap/images/987f8f6c-263a-47b1-a85d-853cfca215d9.svg';
const iconeReact = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg';
const iconeMySql = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg';
const iconeNodeJs = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg';
const iconeDocker = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg';
const iconeTypeScript = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg';
const iconeJest = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jest/jest-plain.svg';
const iconeAngular = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg';
const iconeExpress = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original-wordmark.svg';
const iconeMongoDB = 'https://github.com/joanamds/joanamds/assets/106452876/99a8a0f3-61d0-4903-836e-c10fe7522953';

export const projectsData = [
    {
        id: 0,
        name: 'PIXELS ART',
        imagem: 'https://drive.google.com/uc?export=view&id=1HES0Uo0toFoiCw8ilsSbpGv1SU7m9bFt',
        icones: [iconeJavascript, iconeHTML, iconeCSS],
        iframe: 'https://user-images.githubusercontent.com/104307222/235483773-a8738862-fda3-452d-9c3e-d8f8d32898f6.mp4',
        linkProjeto: 'https://project-pixels-art-ten.vercel.app/',
        linkRepositorio: 'https://github.com/priscilaSartori/project-pixels-art/tree/main',
        linkLinkedin: 'https://www.linkedin.com/posts/priscila-sartori_html-css-javascript-activity-6961667072938389504-Xa5z?utm_source=share&utm_medium=member_desktop',
        empresa: 'TRYBE - MODULO FUNDAMENTOS',
        descricao: 'Implementação de um editor de arte com pixels em que a pessoa usuária poderá escolher uma cor em uma paleta de cores e poderá pintar o que quiser em um quadro branco art artist.',
        habilidades: [
            'Javascript: DOM, seletores, elementos, eventos e web storage'
        ],
        data: '02/08/2022',
    },
    {
        id: 1,
        name: 'TODO LIST',
        imagem: 'https://drive.google.com/uc?export=view&id=1CtTsipu_uwr-2lzkWTxfSI0xcxb8Eo1X',
        icones: [iconeJavascript, iconeHTML, iconeCSS],
        iframe: 'https://user-images.githubusercontent.com/104307222/235514732-700d08e0-787c-4b01-b00f-080fc3b0e03d.webm',
        linkProjeto: 'https://project-todo-list-one.vercel.app/',
        linkRepositorio: 'https://github.com/priscilaSartori/project-todo-list',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO FRONT-END',
        descricao: 'Implementação de uma lista de tarefas usando HTML, CSS e JavaScript.',
        habilidades: [
            'HTML: Estruturação do conteúdo da página.',
            'CSS: Estilização da página.',
            'Javascript: Adição de comportamento dinâmico na página, manipulação do DOM para adicionar e remover itens a lista, utilização de eventos para identificar quando a pessoa está interagindo com a página e a criação de funções para tratar esses eventos de forma apropriada.',
        ],
        data: '10/09/2022',
    },
    {
        id: 2,
        name: 'TELA LOGIN',
        imagem: 'https://drive.google.com/uc?export=view&id=1MvJemBjwiMy25NY1tPfK4SbgWBY4xn4y',
        icones: [iconeJavascript, iconeHTML, iconeCSS, iconeTailwind],
        iframe: '',
        linkProjeto: 'https://project-codante-tela-login-tailwind.vercel.app/',
        linkRepositorio: 'https://github.com/priscilaSartori/project-codante-tela-login-tailwind',
        linkLinkedin: '',
        empresa: 'CODANTE - FRONT-END',
        descricao: 'Desenvolvimento de uma tela de login incrivelmente bonita e responsiva usando o framework Tailwind CSS.',
        habilidades: [
            'Framework Tailwind CSS',
            'React',
        ],
        data: '26/05/2023',
    },
    {
        id: 3,
        name: 'TRYBEWARTS',
        imagem: 'https://github.com/priscilaSartori/project-trybewarts/blob/main/Projeto%20Trybewarts.png?raw=true',
        icones: [iconeJavascript, iconeHTML, iconeCSS, iconeBootstrap],
        iframe: '',
        linkProjeto: 'https://project-trybewarts.vercel.app/',
        linkRepositorio: 'https://github.com/priscilaSartori/project-trybewarts',
        linkLinkedin: 'https://www.linkedin.com/posts/priscila-sartori_html-css-javascript-activity-6964055049199071233-oLL7?utm_source=share&utm_medium=member_desktop',
        empresa: 'TRYBE - MODULO FRONT-END',
        descricao: 'Implementação de uma página de formulário da Escola de Magia de Trybewarts, em que as pessoas estudantes poderão enviar seus feedbacks sobre ela. O tema desse projeto é baseado na obra Harry Potter, de J. K. Rowling, já que programar é o mais próximo que podemos chegar de algo verdadeiramente mágico!',
        habilidades: [
            'HTML',
            'CSS: Formulários e Flexbox',
            'Bibliotecas JavaScript: Bootstrap',
            'Responsividade;',
        ],
        data: '11/08/2022',
    },
    {
        id: 4,
        name: 'SHOPPING CART',
        imagem: 'https://drive.google.com/uc?export=view&id=14BpUCjZZH0OImc0ORtRRbDANTOuWxnpF',
        icones: [iconeJavascript, iconeHTML, iconeCSS],
        iframe: 'https://user-images.githubusercontent.com/104307222/242081382-b83c95e7-3dde-4d36-bcab-febec1ecbed8.mp4',
        linkProjeto: 'https://project-shopping-cart-kohl.vercel.app/',
        linkRepositorio: 'https://github.com/priscilaSartori/project-shopping-cart',
        linkLinkedin: 'https://www.linkedin.com/posts/priscila-sartori_projeto-shopping-cart-proposta-desenvolver-activity-6979996555852279808-exnw?utm_source=share&utm_medium=member_desktop',
        empresa: 'TRYBE - MODULO FRONT-END',
        descricao: 'Desenvolvimento de um carrinho de compras totalmente dinâmico, consumindo dados diretamente de uma API!',
        habilidades: [
            'Javascript assíncrono: Promisses, fetch, async, await e testes assíncronos;',
        ],
        data: '09/09/2022',
    },
    {
        id: 5,
        name: 'TRYUNFO',
        imagem: 'https://github.com/priscilaSartori/project-tryunfo/raw/main/src/images/ImageProjeto2.png',
        icones: [iconeJavascript, iconeHTML, iconeCSS, iconeReact],
        iframe: '',
        linkProjeto: 'https://project-tryunfo-eight.vercel.app/',
        linkRepositorio: 'https://github.com/priscilaSartori/project-tryunfo',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO FRONT-END',
        descricao: 'Desenvolvimento de uma aplicação que seja capaz de adicionar e listar cartas em um baralho no estilo Super Trunfo.',
        habilidades: [
            'Ler o estado de um componente e usá-lo para alterar o que exibimos no browser',
            'Inicializar um componente, dando a ele um estado pré-definido',
            'Atualizar o estado de um componente',
            'Capturar eventos utilizando a sintaxe do React',
            'Criar formulários utilizando sintaxe JSX com as tags: input, textarea, select, form, checkbox',
        ],
        data: '23/09/2022',
    },
    {
        id: 6,
        name: 'TRYBETUNES',
        imagem: 'https://github.com/priscilaSartori/project-trybetunes/blob/main/src/images/TelaAlbum.png?raw=true',
        icones: [iconeJavascript, iconeHTML, iconeCSS, iconeReact],
        iframe: '',
        linkProjeto: 'https://project-trybetunes-five.vercel.app/',
        linkRepositorio: 'https://github.com/priscilaSartori/project-trybetunes',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO FRONT-END',
        descricao: 'Desenvolvimento de uma aplicação capaz de reproduzir músicas das mais variadas bandas e artistas. Essa aplicação será capaz de: fazer login, pesquisar por uma banda ou artista, listar os álbuns disponíveis dessa banda ou artista, visualizar as músicas de um álbum selecionado, reproduzir uma prévia das músicas deste álbum, favoritar e desfavoritar músicas, ver a lista de músicas favoritas, ver o perfil da pessoa logada e editar o perfil da pessoa logada',
        habilidades: [
            'Ciclo de vida de componentes',
            'React Router',
        ],
        data: '30/09/2022',
    },
    {
        id: 7,
        name: 'ONLINE STORE',
        imagem: 'https://drive.google.com/uc?export=view&id=1a0Ddu0Pjo_gH1JS0KBssZWcAuBWPR-Qg',
        icones: [iconeJavascript, iconeHTML, iconeCSS, iconeReact],
        iframe: '',
        linkProjeto: 'https://project-frontend-online-store-rho.vercel.app/',
        linkRepositorio: 'https://github.com/priscilaSartori/project-frontend-online-store',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO FRONT-END',
        descricao: 'Construção do Front-End de um e-commerce, uma loja online, alimentada por uma API do Mercado Livre.',
        habilidades: [
            'Entender o que são Métodos Ágeis',
            'Entender o que é Kanban',
            'Entender o que é Scrum',
            'Trabalhar em equipes utilizando Kanban ou Scrum de maneira eficaz',
            'Praticar todas as habilidades desenvolvidas até agora no módulo de Front-end.',
        ],
        data: '',
    },
    {
        id: 8,
        name: 'TRYBE WALLET',
        imagem: 'https://github.com/priscilaSartori/project-trybewallet/raw/main/src/TelaWallet.png',
        icones: [iconeJavascript, iconeHTML, iconeCSS, iconeReact],
        iframe: '',
        linkProjeto: 'https://project-trybewallet-pi.vercel.app/',
        linkRepositorio: 'https://github.com/priscilaSartori/project-trybewallet',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO FRONT-END',
        descricao: '',
        habilidades: [
            '',
        ],
        data: '',
    },
    {
        id: 9,
        name: 'TRIVIA',
        imagem: 'https://drive.google.com/uc?export=view&id=1a0Ddu0Pjo_gH1JS0KBssZWcAuBWPR-Qg',
        icones: [iconeJavascript, iconeHTML, iconeCSS, iconeReact],
        iframe: '',
        linkProjeto: 'https://project-trivia-w6ua.vercel.app/',
        linkRepositorio: 'https://github.com/priscilaSartori/project-trivia',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO FRONT-END',
        descricao: '',
        habilidades: [
            '',
        ],
        data: '',
    },
    {
        id: 10,
        name: 'STARWARS',
        imagem: 'https://drive.google.com/uc?export=view&id=1a0Ddu0Pjo_gH1JS0KBssZWcAuBWPR-Qg',
        icones: [iconeJavascript, iconeHTML, iconeCSS, iconeReact],
        iframe: '',
        linkProjeto: 'https://project-starwars-nu.vercel.app/',
        linkRepositorio: 'https://github.com/priscilaSartori/project-starwars',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO FRONT-END',
        descricao: '',
        habilidades: [
            '',
        ],
        data: '',
    },
    {
        id: 11,
        name: 'MYSQL ONE FOR ALL',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeMySql],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-mysql-one-for-all',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO BACK-END',
        descricao: '',
        habilidades: [
            '',
        ],
        data: '',
    },
    {
        id: 12,
        name: 'TALKER MANAGER',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeNodeJs],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-talker-manager',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO BACK-END',
        descricao: '',
        habilidades: [
            '',
        ],
        data: '',
    },
    {
        id: 13,
        name: 'STORE MANAGER',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeMySql],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-store-manager',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO BACK-END',
        descricao: '',
        habilidades: [
            '',
        ],
        data: '',
    },
    {
        id: 14,
        name: 'BLOGS API',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeNodeJs],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-blogs-api',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO BACK-END',
        descricao: '',
        habilidades: [
            '',
        ],
        data: '',
    },
    {
        id: 15,
        name: 'MYSQL ALL FOR ONE',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeMySql],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-mysql-all-for-one',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO BACK-END',
        descricao: '',
        habilidades: [
            '',
        ],
        data: '',
    },
    {
        id: 16,
        name: 'DOCKER TODO LIST',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeDocker],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-docker-todo-list',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO BACK-END',
        descricao: '',
        habilidades: [
            '',
        ],
        data: '',
    },
    {
        id: 17,
        name: 'TRYBETS',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeJavascript],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/projeto-trybets',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO C#',
        descricao: '',
        habilidades: [
            '',
        ],
        data: '',
    },
    {
        id: 18,
        name: 'TRYBE HOTEL',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeJavascript],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/projeto-trybe-hotel',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO C#',
        descricao: '',
        habilidades: [
            '',
        ],
        data: '',
    },
    {
        id: 19,
        name: 'TRYBE GAMES',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeJavascript],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-trybe-games',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO C#',
        descricao: '',
        habilidades: [
            '',
        ],
        data: '',
    },
    {
        id: 20,
        name: 'TRYBE BANK',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeJavascript],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-trybank',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO C#',
        descricao: '',
        habilidades: [
            '',
        ],
        data: '',
    },
    {
        id: 21,
        name: 'API DE RECEITAS',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeJavascript],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-api-de-receitas',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO C#',
        descricao: '',
        habilidades: [
            '',
        ],
        data: '',
    },
    {
        id: 22,
        name: 'ALUGUEL DE CARROS',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeJavascript],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-aluguel-de-carros',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO C#',
        descricao: '',
        habilidades: [
            '',
        ],
        data: '',
    },
    {
        id: 23,
        name: 'TRYBE FUTEBOL CLUBE',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeTypeScript, iconeHTML, iconeCSS, iconeDocker],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-trybe-futebol-clube',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO BACK-END',
        descricao: '',
        habilidades: [
            '',
        ],
        data: '',
    },
    {
        id: 24,
        name: 'RESTAURANT ORDERS',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeTypeScript],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-restaurant-orders',
        linkLinkedin: '',
        empresa: 'TRYBE - PYTHON',
        descricao: '',
        habilidades: [
            '',
        ],
        data: '',
    },
    {
        id: 25,
        name: 'TING',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeTypeScript],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-ting',
        linkLinkedin: '',
        empresa: 'TRYBE - PYTHON',
        descricao: '',
        habilidades: [
            '',
        ],
        data: '',
    },
    {
        id: 26,
        name: 'DELIVERY APP',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeTypeScript, iconeHTML, iconeCSS, iconeDocker],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-delivery-app',
        linkLinkedin: '',
        empresa: 'TRYBE - FULL-STACK',
        descricao: '',
        habilidades: [
            '',
        ],
        data: '',
    },
    {
        id: 27,
        name: 'RECIPES APP',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeJavascript, iconeReact, iconeJest],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-recipes-app',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO FRONT-END',
        descricao: 'Desenvolvimento de um app de receitas, utilizando o que há de mais moderno dentro do ecossistema React: Hooks e Context API! Nele será possível: ver, buscar, filtrar, favoritar e acompanhar o progresso de preparação de receitas de comidas e bebidas!',
        habilidades: [
            'A base de dados serão 2 APIs distintas, uma para comidas e outra para bebidas',
            'O layout tem como foco dispositivos móveis, dessa forma todos os protótipos vão estar desenvolvidos em telas menores.',
        ],
        data: '15/12/2022',
    },
    {
        id: 28,
        name: 'MOMENTS',
        imagem: 'https://github.com/priscilaSartori/project-moments/raw/main/moments/mock-moment-images/home.png',
        icones: [iconeAngular, iconeExpress],
        iframe: '',
        linkProjeto: 'https://project-moments-amber.vercel.app/',
        linkRepositorio: 'https://github.com/priscilaSartori/project-moments',
        linkLinkedin: '',
        empresa: 'HORA DE CODAR - FULL-STACK',
        descricao: 'Desenvolvimento de aplicação full-stack para o registro de momentos com os amigos e comentários, como o instagram.',
        habilidades: [
            'Página Home: Para a exibição dos momentos com busca de momentos (através de filtro)',
            'Página Detalhes: Para conhecer melhor o momento acessado, com relação entre tabelas 1:N para os comentários',
            'Página Edição: Para a edição dos momentos',
            'Página Sobre: Descrição sobre a aplicação',
        ],
        data: '23/07/2023',
    },
    {
        id: 29,
        name: 'DASHBOARD',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeAngular, iconeExpress],
        iframe: '',
        linkProjeto: 'https://dashboard-fullstack-angular-express.vercel.app/',
        linkRepositorio: 'https://github.com/priscilaSartori/dashboard-fullstack-angular-express',
        linkLinkedin: '',
        empresa: 'PESSOAL - FULL-STACK',
        descricao: '',
        habilidades: [
            '',
        ],
        data: '',
    },
    {
        id: 30,
        name: 'ALGORITHMS',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeTypeScript],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-algorithms',
        linkLinkedin: '',
        empresa: 'TRYBE - PYTHON',
        descricao: 'Soluções para os mais diversos problemas do dia a dia e otimização de algoritmos.',
        habilidades: [
            'Lógica',
            'Capacidade de interpretação de problemas',
            'Capacidade de interpretação de um código legado',
            'Capacidade de otimizar a resolução de problemas e',
            'Resolver problemas/Otimizar algoritmos sob pressão',
        ],
        data: '31/05/2023',
    },
    {
        id: 31,
        name: 'CAR SHOP',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeTypeScript, iconeDocker],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-car-shop',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO BACK-END',
        descricao: 'Desenvolvimento de uma API com CRUD para gerenciar uma concessionária de veículos, aplicando os princípios de Programação Orientada a Objetos (POO) e usando o banco de dados MongoDB através do framework do Mongoose.',
        habilidades: [
            'API orientada a objetos',
            'NoSQL',
        ],
        data: '27/04/2023',
    },
    {
        id: 32,
        name: 'MONGODB',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeMongoDB],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-mongodb-commerce',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO BACK-END',
        descricao: 'Desenvolvimento de um banco de dados commerce, que contém dados do cardápio do McDonalds, como ingredientes, valores nutricionais e dados fictícios de vendas.',
        habilidades: [
            'MongoDB: Filter operators, operadores de consulta, updates simples e complexos.',
        ],
        data: '14/04/2023',
    },
    {
        id: 33,
        name: 'TRYBERS AND DRAGONS',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeTypeScript],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-trybers-and-dragons',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO BACK-END',
        descricao: 'Desenvolvimento de uma estrutura de jogos de interpretação de papéis, mais conhecidos como jogos RPG (Role Playing Game), aplicando os princípios da arquitetura SOLID e os princípios de POO.',
        habilidades: [
            'POO: Programação orientada a objetos',
            'Solid',
            'Herança e Composição',
            'Poliformismo',
        ],
        data: '28/03/2023',
    },
    {
        id: 34,
        name: 'TRYBESMITH',
        imagem: 'https://www.ishir.com/wp-content/webp-express/webp-images/uploads/2023/03/backend-development-languages-ISHIR.png.webp',
        icones: [iconeTypeScript],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-trybesmith',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO BACK-END',
        descricao: 'Desenvolvimento de uma loja de itens medievais, no formato de uma API, utilizando Typescript. Desenvolvimento de todas as camadas da aplicação (Models, Service e Controllers) e, por meio dessa aplicação, a realização das operações básicas que se pode fazer em um determinado banco de dados: Criação, Leitura, Atualização e Exclusão (ou CRUD, para as pessoas mais íntimas stuck_out_tongue_winking_eye - Create, Read, Update e Delete). Criação de alguns endpoints que irão ler e escrever em um banco de dados, utilizando o MySQL.',
        habilidades: [
            'TypeScript',
            'Tipagem Estática e Generics',
            'Express com TypeScript',
        ],
        data: '14/03/2023',
    },
    {
        id: 35,
        name: 'LESSONS LEARNED',
        imagem: 'https://github.com/priscilaSartori/project-lessons-learned/blob/main/project-lessons-learned.png?raw=true',
        icones: [iconeHTML, iconeCSS],
        iframe: '',
        linkProjeto: 'https://project-lessons-learned-eight.vercel.app/',
        linkRepositorio: 'https://github.com/priscilaSartori/project-lessons-learned',
        linkLinkedin: 'https://www.linkedin.com/posts/priscila-sartori_html-css-vqv-activity-6955365063578791936-oHSg?utm_source=share&utm_medium=member_desktop',
        empresa: 'TRYBE - MODULO FUNDAMENTOS',
        descricao: 'Foi desenvolvido uma página HTML posicionada e estilizada com CSS. Um site que contém uma série de informações sobre o que aprendi na Trybe ao longo dos primeiros três blocos. O site possui elementos posicionados e estilizados e, além disso, contém semântica apropriada para que seja acessível e melhor ranqueado.',
        habilidades: [
            'HTML: Estruturas de página',
            'CSS: Seletores e posicionamento',
        ],
        data: '18/07/2022',
    },
    {
        id: 36,
        name: 'PLAYGROUND FUNCTIONS',
        imagem: 'https://github.com/priscilaSartori/project-playground-functions/blob/main/Playground.png?raw=true',
        icones: [iconeHTML, iconeCSS],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-playground-functions',
        linkLinkedin: 'https://www.linkedin.com/posts/priscila-sartori_html-css-javascript-activity-6958589075519885312-gdnu?utm_source=share&utm_medium=member_desktop',
        empresa: 'TRYBE - MODULO FUNDAMENTOS',
        descricao: 'Implementação do código de funções que resolvem problemas com respostas pré-determinadas utilizando a lógica de programação para na análise de cada problema e resposta esperada, facilitando a implementação do código de cada uma das funções.',
        habilidades: [
            'Javascript: Array, loop for, funções, objetos, let, const, arrow functions e template literals;',
        ],
        data: '25/07/2022',
    },
    {
        id: 37,
        name: 'JS UNIT TESTS',
        imagem: 'https://media.licdn.com/dms/image/C4D22AQFEG1J_0JDq0w/feedshare-shrink_1280/0/1661395317654?e=1698883200&v=beta&t=ei0vnq-xGvGmTpFJnd2ri7LHhzVGEEO2zyGnqMgZoO0',
        icones: [iconeHTML, iconeCSS],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-js-unit-tests',
        linkLinkedin: 'https://www.linkedin.com/posts/priscila-sartori_testesunitaerrios-jest-nodejs-activity-6968397032306675712-Ztkj?utm_source=share&utm_medium=member_desktop',
        empresa: 'TRYBE - MODULO FUNDAMENTOS',
        descricao: 'Implementação de várias funções na resolução dos requisitos propostos e/ou testes unitários para garantir que as implementações das funções estão corretas, de acordo com o que está sendo solicitado em cada enunciado.',
        habilidades: [
            'Escrever testes unitários utilizando o módulo Jest do NodeJS para verificar o correto funcionamento das funções',
            'Escrever funções de forma que elas atendam a testes já implementados',
            'Escrever testes e funções utilizando uma abordagem de desenvolvimento orientado a testes',
        ],
        data: '16/08/2022',
    },
    {
        id: 38,
        name: 'ZOO FUNCTIONS',
        imagem: 'https://media.licdn.com/dms/image/C4D22AQEMG6ZZz6paCw/feedshare-shrink_2048_1536/0/1662834125781?e=1698883200&v=beta&t=tv6cocAjq0phEf2x5QiDPrlDUNk-XKStToYdqPx0SLE',
        icones: [iconeHTML, iconeCSS],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-zoo-functions-project',
        linkLinkedin: 'https://www.linkedin.com/posts/priscila-sartori_jest-javascript-vqv-activity-6974431827742584832-bb_L?utm_source=share&utm_medium=member_desktop',
        empresa: 'TRYBE - MODULO FUNDAMENTOS',
        descricao: 'Desenvolvimento de funções que buscam informações sobre os animais do zoológico como: espécie e local de origem. Além disso, buscam dados sobre as pessoas que colaboram com a manutenção e cuidado do zoológico.',
        habilidades: [
            'Higher Order Functions: sort,map, filter, reduce, spread operator, rest parameters e object destructuring, array destructuring, default destructuring, object property shorthand e default parameters',
            'ES6',
            'tests',
        ],
        data: '25/08/2022',
    },
    {
        id: 39,
        name: 'SOLAR SYSTEM',
        imagem: 'https://github.com/priscilaSartori/project-solar-system/blob/main/Imagem%20Projeto.png?raw=true',
        icones: [iconeHTML, iconeCSS],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-solar-system',
        linkLinkedin: 'https://www.linkedin.com/posts/priscila-sartori_projeto-solar-system-proposta-desenvolver-activity-6980000864237170688-0GnZ?utm_source=share&utm_medium=member_desktop',
        empresa: 'TRYBE - MODULO FUNDAMENTOS',
        descricao: 'Desenvolvimento de um modelo do sistema solar! Ao utilizar essa aplicação, uma pessoa usuária deverá ser capaz de visualizar todos os planetas do sistema solar renderizados na tela e visualizar todas as cartas com informações sobre missões espaciais;',
        habilidades: [
            'Utilizar JSX no React',
            'Utilizar corretamente o método render() para renderizar seus componentes',
            'Utilizar import para trazer componentes em diferentes arquivos',
            'Criar componentes de classe em React',
            'Criar múltiplos componentes a partir de um array',
            'Fazer uso de props corretamente',
            'Fazer uso de PropTypes para validar as props de um componente.',
        ],
        data: '20/09/2022',
    },
    {
        id: 40,
        name: 'REACT TESTING LIBRARY',
        imagem: 'https://media.licdn.com/dms/image/C4D22AQE9-amtBE9HXQ/feedshare-shrink_800/0/1666479521173?e=1698883200&v=beta&t=cv7ddTTyA1_mWMea2Fnn7LzdL-sRjUdSPrQZwBL7MVw',
        icones: [iconeHTML, iconeCSS],
        iframe: '',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-react-testing-library',
        linkLinkedin: 'https://www.linkedin.com/posts/priscila-sartori_projeto-react-testing-library-proposta-activity-6989721727912022016-NE7r?utm_source=share&utm_medium=member_desktop',
        empresa: 'TRYBE - MODULO FUNDAMENTOS',
        descricao: 'Desenvolvimento de testes para uma aplicação React que já está criada e configurada, utilizando Jest e a biblioteca React Testing Library. A aplicação contém uma implementação completa de todos os requisitos da Pokédex. Assim, para cada requisito listado, foi escrito testes que garantam sua corretude.',
        habilidades: [
            'Utilizar os seletores (queries) da React-Testing-Library em testes automatizados',
            'Simular eventos com a React-Testing-Library em testes automatizados',
            'Testar fluxos lógicos assíncronos com a React-Testing-Library',
            'Escrever testes que permitam a refatoração da estrutura dos componentes da aplicação sem necessidade de serem alterados',
            'Testar inputs.',
        ],
        data: '',
    },
]

