const iconeJavascript = 'https://upload.vectorlogo.zone/logos/javascript/images/239ec8a4-163e-4792-83b6-3f6d96911757.svg';
const iconeHTML = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg';
const iconeCSS = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg';
const iconeTailwind = 'https://user-images.githubusercontent.com/106452876/222272710-d163957e-5ec1-4d91-b0b0-501287eb56a4.svg';
const iconeBootstrap = 'https://upload.vectorlogo.zone/logos/getbootstrap/images/987f8f6c-263a-47b1-a85d-853cfca215d9.svg';
const iconeReact = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg';
const iconeMySql = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg';
const iconeNodeJs = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg';
const iconeDocker = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg';
const iconeTypeScript = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg';
const iconeJest = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jest/jest-plain.svg';
const iconeAngular = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg';
const iconeExpress = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original-wordmark.svg';
const iconeMongoDB = 'https://github.com/joanamds/joanamds/assets/106452876/99a8a0f3-61d0-4903-836e-c10fe7522953';

export const projectsData = [
    {
        id: 0,
        name: 'PIXELS ART',
        imagem: 'https://drive.google.com/uc?export=view&id=1HES0Uo0toFoiCw8ilsSbpGv1SU7m9bFt',
        icones: [iconeJavascript, iconeHTML, iconeCSS],
        iframe: 'https://user-images.githubusercontent.com/104307222/235483773-a8738862-fda3-452d-9c3e-d8f8d32898f6.mp4',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-pixels-art/tree/main',
        linkLinkedin: 'https://www.linkedin.com/posts/priscila-sartori_html-css-javascript-activity-6961667072938389504-Xa5z?utm_source=share&utm_medium=member_desktop',
        empresa: 'TRYBE - MODULO FUNDAMENTOS',
        descricao: 'Implementação de um editor de arte com pixels em que a pessoa usuária poderá escolher uma cor em uma paleta de cores e poderá pintar o que quiser em um quadro branco art artist.',
        habilidades: [
            'Javascript: DOM, seletores, elementos, eventos e web storage'
        ],
        data: '02/08/2022',
    },
    {
        id: 1,
        name: 'TODO LIST',
        imagem: 'https://drive.google.com/uc?export=view&id=1CtTsipu_uwr-2lzkWTxfSI0xcxb8Eo1X',
        icones: [iconeJavascript, iconeHTML, iconeCSS],
        iframe: 'https://user-images.githubusercontent.com/104307222/235514732-700d08e0-787c-4b01-b00f-080fc3b0e03d.webm',
        linkProjeto: '',
        linkRepositorio: 'https://github.com/priscilaSartori/project-todo-list',
        linkLinkedin: '',
        empresa: 'TRYBE - MODULO FRONT-END',
        descricao: 'Implementação de uma lista de tarefas usando HTML, CSS e JavaScript.',
        habilidades: [
            'HTML: Estruturação do conteúdo da página.',
            'CSS: Estilização da página.',
            'Javascript: Adição de comportamento dinâmico na página, manipulação do DOM para adicionar e remover itens a lista, utilização de eventos para identificar quando a pessoa está interagindo com a página e a criação de funções para tratar esses eventos de forma apropriada.',
        ],
        data: '10/09/2022',
    },
    // {
    //     id: 3,
    //     name: 'TELA LOGIN',
    //     imagem: 'https://drive.google.com/uc?export=view&id=1MvJemBjwiMy25NY1tPfK4SbgWBY4xn4y',
    //     icones: [iconeJavascript, iconeHTML, iconeCSS, iconeTailwind],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'CODANTE - FRONT-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 4,
    //     name: 'TRYBEWARTS',
    //     imagem: 'https://github.com/priscilaSartori/project-trybewarts/blob/main/Projeto%20Trybewarts.png?raw=true',
    //     icones: [iconeJavascript, iconeHTML, iconeCSS, iconeBootstrap],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO FRONT-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 5,
    //     name: 'SHOPPING CART',
    //     imagem: 'https://drive.google.com/uc?export=view&id=14BpUCjZZH0OImc0ORtRRbDANTOuWxnpF',
    //     icones: [iconeJavascript, iconeHTML, iconeCSS],
    //     iframe: 'https://user-images.githubusercontent.com/104307222/242081382-b83c95e7-3dde-4d36-bcab-febec1ecbed8.mp4',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO FRONT-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 6,
    //     name: 'TRYUNFO',
    //     imagem: 'https://github.com/priscilaSartori/project-tryunfo/raw/main/src/images/ImageProjeto2.png',
    //     icones: [iconeJavascript, iconeHTML, iconeCSS, iconeReact],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO FRONT-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 7,
    //     name: 'TRYBETUNES',
    //     imagem: 'https://github.com/priscilaSartori/project-trybetunes/blob/main/src/images/TelaAlbum.png?raw=true',
    //     icones: [iconeJavascript, iconeHTML, iconeCSS, iconeReact],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO FRONT-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 8,
    //     name: 'ONLINE STORE',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeJavascript, iconeHTML, iconeCSS, iconeReact],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO FRONT-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 9,
    //     name: 'TRYBE WALLET',
    //     imagem: 'https://github.com/priscilaSartori/project-trybewallet/raw/main/src/TelaWallet.png',
    //     icones: [iconeJavascript, iconeHTML, iconeCSS, iconeReact],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO FRONT-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 10,
    //     name: 'TRIVIA',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeJavascript, iconeHTML, iconeCSS, iconeReact],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO FRONT-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 11,
    //     name: 'STARWARS',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeJavascript, iconeHTML, iconeCSS, iconeReact],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO FRONT-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 12,
    //     name: 'MYSQL ONE FOR ALL',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeMySql],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO BACK-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 13,
    //     name: 'TALKER MANAGER',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeNodeJs],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO BACK-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 14,
    //     name: 'STORE MANAGER',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeMySql],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO BACK-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 15,
    //     name: 'BLOGS API',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeNodeJs],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO BACK-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 16,
    //     name: 'MYSQL ALL FOR ONE',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeMySql],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO BACK-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 17,
    //     name: 'DOCKER TODO LIST',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeDocker],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO BACK-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 18,
    //     name: 'TRYBETS',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeJavascript],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO C#',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 19,
    //     name: 'TRYBE HOTEL',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeJavascript],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO C#',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 20,
    //     name: 'TRYBE GAMES',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeJavascript],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO C#',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 21,
    //     name: 'TRYBE BANK',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeJavascript],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO C#',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 22,
    //     name: 'API DE RECEITAS',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeJavascript],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO C#',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 23,
    //     name: 'ALUGUEL DE CARROS',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeJavascript],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO C#',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 24,
    //     name: 'TRYBE FUTEBOL CLUBE',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeTypeScript, iconeHTML, iconeCSS, iconeDocker],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO BACK-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 25,
    //     name: 'RESTAURANT ORDERS',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeTypeScript],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - PYTHON',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 26,
    //     name: 'TING',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeTypeScript],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - PYTHON',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 27,
    //     name: 'DELIVERY APP',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeTypeScript, iconeHTML, iconeCSS, iconeDocker],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - FULL-STACK',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 28,
    //     name: 'RECIPES APP',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeJavascript, iconeReact, iconeJest],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO FRONT-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 29,
    //     name: 'MOMENTS',
    //     imagem: 'https://github.com/priscilaSartori/project-moments/raw/main/moments/mock-moment-images/home.png',
    //     icones: [iconeAngular, iconeExpress],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'HORA DE CODAR - FULL-STACK',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 30,
    //     name: 'DASHBOARD',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeAngular, iconeExpress],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'PESSOAL - FULL-STACK',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 31,
    //     name: 'ALGORITHMS',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeTypeScript],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - PYTHON',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 32,
    //     name: 'CAR SHOP',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeTypeScript, iconeDocker],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO BACK-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 33,
    //     name: 'MONGODB',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeMongoDB],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO BACK-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 34,
    //     name: 'TRYBERS AND DRAGONS',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeTypeScript],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO BACK-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
    // {
    //     id: 34,
    //     name: 'TRYBESMITH',
    //     imagem: 'https://drive.google.com/uc?export=view&id=xxxxxxxxxxxxxxxxxx',
    //     icones: [iconeTypeScript],
    //     iframe: '',
    //     linkProjeto: '',
    //     linkRepositorio: 'https://github.com/priscilaSartori/xxxxxxxxxxxxxx',
    //     linkLinkedin: '',
    //     empresa: 'TRYBE - MODULO BACK-END',
    //     descricao: '',
    //     habilidades: [
    //         '',
    //     ],
    //     data: '',
    // },
]

